// components/ui/input.tsx
import * as React from "react";

import { cn } from "@/lib/cn";

function Input({ className, type, ...props }: React.ComponentProps<"input">) {
  return (
    <input
      type={type}
      data-slot="input"
      className={cn(
        "t-input h-11 w-full min-w-0 rounded-md border border-input bg-card px-3.5 py-1.5 text-base shadow-[var(--shadow-control)] transition-[background-color,color,border-color,box-shadow] duration-[var(--motion-control)] ease-[var(--ease-move)] outline-none hover:border-foreground/12 focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring/40 selection:bg-primary selection:text-primary-foreground file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
        "focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring/40",
        "aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40",
        className,
      )}
      {...props}
    />
  );
}

export { Input };

// src/components/ui/input/Input.vue
<script setup lang="ts">
import { ref } from 'vue'
import { cn } from '@/lib/cn'

withDefaults(defineProps<{
  modelValue?: string
  class?: string
  placeholder?: string
  type?: string
  disabled?: boolean
}>(), {
  modelValue: '',
  class: '',
  placeholder: '',
  type: 'text',
  disabled: false,
})
defineEmits<{
  'update:modelValue': [value: string]
}>()

const el = ref<HTMLInputElement | null>(null)

function focus() {
  el.value?.focus()
}

defineExpose({ focus, el })
</script>

<template>
  <input
    ref="el"
    :type="type"
    :value="modelValue"
    :placeholder="placeholder"
    :disabled="disabled"
    :class="
      cn(
        'surface-control min-h-11 w-full px-4 py-3 text-ink-950 dark:text-ink-50 text-sm placeholder-ink-400 dark:placeholder-ink-600 focus:outline-none focus:ring-2 focus:ring-accent-primary/20 disabled:cursor-not-allowed disabled:opacity-40 transition-[color,background-color,border-color,box-shadow,opacity] duration-200',
        $props.class,
      )
    "
    @input="$emit('update:modelValue', ($event.target as HTMLInputElement).value)"
  >
</template>
